### ISSUE TITLE
cordova run android crash

### ISSUE THREAD

**Issue by guillaumevincent** [Rudloff/lesspass-cordova#1]
![image](https://cloud.githubusercontent.com/assets/943762/21226194/b0a7f2f8-c2d4-11e6-8af3-fb0eb685ac00.png)

cordova --version
6.4.0

node --version
v6.9.1

any idea ?

**Comment by Rudloff** [comment]
Hum, I can't reproduce.
Can you use `adb logcat` to print logs from the emulator/device please?

**Comment by Rudloff** [comment]
Also, does it crash too when you install from [the release APK](https://github.com/Rudloff/lesspass-cordova/releases/download/0.1.1/android-debug.apk)?

**Comment by guillaumevincent** [comment]
The HelloWorld cordova crash too
Not related to your app.

probably my virtual image is not good
